name: CI

on: 
  release:
    types: [published, created, edited]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Run a multi-line script
      run: |
        echo RELEASE
        cat $GITHUB_EVENT_PATH
